### PR TITLE
CI_COMMIT_REF_SLUG instead of CI_COMMIT_REF_NAME to support / in branch name (closes #4)

### LINKED ISSUE #4: Fails on / in branch names
```
$ docker build --cache-from $CI_DEV_IMAGE_WITH_TAG --tag $CI_DEV_IMAGE_WITH_TAG --target dev .
invalid argument "registry.gitlab.com/project/repo/dev:ci/behat" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR: Job failed: exit code 125
```

I think `$CI_COMMIT_REF_SLUG` should be used instead of `$CI_COMMIT_REF_NAME`: https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables. The SLUG is stripped from anything that is potentially incompatible I think.

### PR DESCRIPTION
**Pull request by stefandoorn**

### CODE REVIEW

**Review by covex-nn — APPROVED** [review]

**Comment by covex-nn** [comment]
CI failed, but it's my fault (i'll fix it later)

**Comment by covex-nn** [comment]
Thank you, @stefandoorn !

**Comment by covex-nn** [comment]
I thought, that `if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then exit 0; fi` will successfuly stop build step execution for PRs, but somehow it did not happend =(

> `TRAVIS_PULL_REQUEST` is set to the pull request number if the current job is a pull request build, or `false` if it’s not.

**Comment by stefandoorn** [comment]
Hm, not sure about that. But isn't it a good idea to build all PR's? I've also internally adjusted the code to run build/phpunit steps e.g. on each commit, instead of only on `master`. Reasoning is that I want to know issues as soon as possible, not just when willing to deploy :-)

**Comment by covex-nn** [comment]
Docker cache is not available for PRs. It cannot be prepared, stored to registry and used on latest stages, so i planed to skip these steps for PRs.

I fixed it in #6 :tada: There is another variable `$TRAVIS_SECURE_ENV_VARS`, and it is equal to `false` for builds from forks )

**Pull request merged**
